name: CraftEngineViaCompatibility
version: "${version}"
main: net.momirealms.craftengine.viacompat.CraftEngineViaCompatibilityPlugin
api-version: "1.21.11"
load: STARTUP
authors:
  - XiaoMoMi
description: Adds persistent server and client registry IDs plus custom collision shapes for CraftEngine blocks.
dependencies:
  server:
    CraftEngine:
      load: BEFORE
      required: true
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: true
      join-classpath: true
    ViaBackwards:
      load: BEFORE
      required: true
      join-classpath: true
